spring.datasource.url=jdbc:mysql://localhost:3306/sigmac_db
spring.datasource.username=root
spring.datasource.password=maycol9533223
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080